# -*- coding: utf-8 -*-
"""Lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eP4YIN0zmDJzQo0B7EtyKLvIblRzv_kO
"""

name ="cR leo"
surname= "Messi"
print("Hello " + surname.title() + "!")

"""**use of \n & \t**"""

print("\tmessi")
print("messi\nis\na\nfootball player")

"""**stripping of spaces**"""

name=" nameless "
name.rstrip()
name = name.rstrip()
name.lstrip()
name.strip()

print('use of apostrophe')
**print("apostrophe's uses ")

9**2 # ** are used for exponents(raising power)
2+3*4 #python follows BODMAS
print("5+3")
print(5+3)

age=21
print("happy "+ str(age) + "st birthday")

import this

"""**LISTS**"""

colors=['red','blue','yellow']
print(colors)
print(colors[1].title())
print(colors[-1])
print("my favorite color is " + colors[0].title())

colors[2]='black'

colors.append('green')
print(colors)

alphabets=[]
alphabets.append('a')
alphabets.append('b')
alphabets.append('c')
print(alphabets)
alphabets.insert(1,'d')
print(alphabets)
del alphabets[1]
print(alphabets)
alphabets.extend(['d','e'])
print(alphabets)

ex_color=colors.pop()
print(ex_color)

print(colors)
print("the color I removed is "+ ex_color)

elements=['fire','water','air','earth','light','darkness']
print("my elemental affinity is "+ elements.pop(-1))
print(elements)
holy_element='light'
elements.remove(holy_element)
print("the "+ holy_element + " element is exclusive to the Hero.")

print(elements)

guests=['king','prince','archbishop','knight captain ','hero']
for i in range(len(guests)):

  print(guests[i].title() + ",I would like to invite you for the banquet after defeating the demon king.\n")


for i in guests:
  print(i)

unavailable=guests.pop(3)
guests.insert(3,'guildmaster')
print("Unfortunately, The " + unavailable + " will not be able to attend the banquet.")
for i in range(len(guests)):
  print(guests[i].title() + ",I would like to invite you to a banquet.\n ")

guests.insert(0,'Saintess')
guests.insert(4,'Duke')
guests.append('Empress')

for i in range(len(guests)):
  print(guests[i].title() + ",I would like to invite you to a banquet.\n ")

print("Monsters are attacking, there's no time for banquet: Go fight for the country")
for i in range(len(guests)-2):
  print("TATAKAE!!! "+ guests.pop())

for i in range(len(guests)):
  print(guests[i].title() + ",Enjoy the feast.")
  
del guests[0]

print(guests)

ranks=['F','D','A','B','C','E']
ranks.reverse()
print(ranks)

ranks.sort()
print(ranks)
ranks.sort(reverse=True) # reversing the order
print(ranks)

print(sorted(ranks))   #temporary sort 

print(ranks)
print(len(ranks))

print(sorted(ranks,reverse=True))
print(ranks )

weapons=['sword','spear','short sword','bow','knuckles']
for weapon in weapons:
  print(weapon)

food=['dumplings','soup','pork','beef']
for item in food:
  print(item)

for i in food:
  print("I like "+ i +"!\n")

numb=list(range(1,7))
print(numb)

even1=list(range(2,15,2))
print(even1)
min(even1)

cube1=[]
for cube in range(1,11):
  cube1.append(cube**3)
print(cube1)

weapons=['sword','knuckles','spear','short sword','bow']
print(weapons[0:3])
print(weapons[2:])
print(weapons[:5])

for weapon in weapons[2:]:
  print("I can use "+ weapon.title())

melee=weapons[:4]
print(melee)

"""**Tuples**"""

combat=(100,120,130)
print(combat[2])